// GENERATED by scripts/gen-casv-format.mjs — do not edit by hand.
// Source of truth: crates/raw-pipeline/src/casa_video.rs
// Re-run `node scripts/gen-casv-format.mjs` after changing Rust constants.

export const CASV_MAGIC = 0x56415343;
export const CASV_VERSION = 1;
export const CASV_HEADER_BYTES = 32;
export const CASV_INDEX_ENTRY_BYTES = 8;
export const CASV_PFRAME_FLAG = 0x80000000;
export const CASV_BBOX_FLAG = 0x40000000;
export const CASV_TILE_FLAG = 0x20000000;
export const CASV_REPLACE_FLAG = 0x10000000;
export const CASV_HDR_FABLE_FLAG = 0x00000002;
export const CASV_TILE_V2_BIT = 0x00008000;
export const CASV_HDRFLAG_LOSSY = 0x00000001;
export const CASV_FOOTER_MAGIC = 0x46534143;
export const CASV_FOOTER_BYTES = 32;
export const CASV_AUDIO_BOX_MAGIC = 0x55415343;
export const CASV_RATE_BOX_MAGIC = 0x52534143;
