import json

with open('docs/ecosystem-map.model.json', encoding='utf-8') as f:
    m = json.load(f)

updates = {

"run_prog_fn": """run_progressive_into (lines 638-767) is the private unsafe engine powering decode_progressive — the one place in the codebase where JPEG XL's pass-by-pass progressive capability is driven. Like run_full_into for the non-progressive path, it is the single authoritative implementation of the libjxl call sequence for progressive decoding, so every public method that needs progressive behaviour funnels through it.

Why it is private and unsafe: it holds a raw *mut JxlDecoder pointer aliased out of the Decoder struct, drives it directly without the reset discipline (the public wrapper owns reset), and calls set_len on uninitialised memory for the zero-copy-out trick. Making it public would let callers bypass the reset-on-every-path guarantee and leave the handle poisoned on failure.

How it works, step by step. Setup mirrors run_full_into: attach the thread runner (if parallel), optionally set keep_orientation. It then subscribes to four events — BASIC_INFO, FRAME_PROGRESSION, FULL_IMAGE, and NEED_IMAGE_OUT_BUFFER — via JxlDecoderSubscribeEvents. Critically, it also calls JxlDecoderSetProgressiveDetail(kPasses), which instructs libjxl to signal S_PROG after each refinement pass (DC, full-res AC group passes, detail passes) rather than only at the final full image. Without this call, S_PROG events are never emitted and decode_progressive degenerates to a slow full decode with no intermediate frames. After JxlDecoderSetInput (zero-copy in — libjxl reads the caller's slice in place) and CloseInput, the processing loop begins.

The loop branches on JxlDecoderProcessInput's typed status. On S_BASIC: reads JxlBasicInfo, fills DecodedMeta, and runs the decompression-bomb guard using checked_mul (overflow-safe). The guard fires here, before any large allocation, matching run_full_into's contract. On S_NEEDOUT: asks JxlDecoderImageOutBufferSize for the exact required buffer size, validates it is non-zero and a clean multiple of size_of::<S>(), then does the zero-copy-out allocation: buf.clear(); buf.reserve(elems); buf.set_len(elems); — and then, unlike run_full_into, immediately zeroes the buffer with write_bytes before binding it with SetImageOutBuffer. The zeroing is mandatory here: a progressive flush exposes a buffer libjxl has only partially filled, and reading the unfilled bytes would be undefined behaviour. run_full_into skips zeroing on the success path (it knows the full buffer will be written before returning); this path cannot make that guarantee. On S_PROG: the pass counter is incremented unconditionally before the flush attempt, so the counter stays in sync with decoder-signalled events even when FlushImage fails (a failed flush is not an error — it means the pass produced no new data). If FlushImage succeeds and w/h are non-zero, the callback is invoked with DecodeEvent::Progress { pass: this_pass, width: w, height: h, pixels: &buf } — a borrowed slice into the live output buffer. If the callback returns ProgressControl::Stop, the loop breaks and the best-so-far image is returned. On S_FULL or S_SUCCESS: break (the full image is in buf). On S_NEEDIN with allow_partial: break with best-so-far; without: return DecodeError::Process.

After the loop, a final guard checks w==0 || h==0 || buf.is_empty() and returns an error if so (a pathological stream could reach here without ever having produced a valid output buffer). The return is Image { width: w, height: h, channels, data: buf, extra: Vec::new(), meta } — note that extra channels are never read back in the progressive path; the focus is on delivering pixel passes fast, not on ancillary planes. The comment at line 755 explains why DecodeEvent::Final is NOT emitted before returning: the caller already has the final pixels as the return value, and cloning them into a Final event would double peak memory (80 MB for a 20 MP RGBA8 image).

Gotchas: (1) The zeroing at S_NEEDOUT is non-negotiable — remove it and the first progressive frame's unfilled regions contain arbitrary heap bytes. (2) pass increments before the FlushImage check, so the first Progress event always carries pass=0 regardless of whether earlier passes failed. (3) Cooperative cancellation (is_cancelled()) is checked at the top of every loop iteration — it can fire between any two status events. (4) The handle is NOT reset inside this function; the public wrapper decode_progressive owns that reset. (5) extra: Vec::new() in the return is intentional — use Decoder::decode for extra channels.""",

"compat_prog_fn": """decode_progressive_frames_borrowed (lines 863-960) is the legacy free-function progressive driver that predates the Decoder object API. Where decode_progressive works through a reusable Decoder, this function constructs and drives a raw *mut JxlDecoder directly, keeping the old call-site shape: you give it a byte slice and a FnMut callback, it fires the callback for each partial frame as borrowed bytes, and returns Option<(f64, f64)> — (time_to_first_usable_pixel_ms, total_wall_ms).

Why it exists alongside the object API: bench, test, and integration call sites written against jxl_lowlevel.rs used this exact signature. Rewriting them all to use Decoder + DecodeEvent<S> at the same time as the codec rewrite was a scope risk. The free-function is the compatibility shim; new code should use Decoder::decode_progressive.

How it works. The function creates a JxlDecoder directly (JxlDecoderCreate), subscribes to BASIC_INFO | FRAME_PROGRESSION | NEED_IMAGE_OUT_BUFFER | FULL_IMAGE, and calls JxlDecoderSetProgressiveDetail(kPasses) so libjxl signals per-pass. It sets the input bytes (zero-copy: as_ptr/len into the caller's slice) and calls CloseInput before entering the loop, so libjxl never stalls on JXL_DEC_NEED_MORE_INPUT for a complete in-memory codestream — a subtle but important detail that avoids the 'decoder hangs forever' failure mode on fully-buffered inputs.

The processing loop: on S_BASIC reads image dimensions from JxlBasicInfo; on S_NEEDOUT sizes the output buffer via JxlDecoderImageOutBufferSize and allocates/zeroes/binds it (same zero-fill discipline as run_progressive_into — partial flushes expose uninitialised bytes); on S_PROG calls JxlDecoderFlushImage and, on success, fires the callback with DecodeProgressiveEvent::Progress { width, height, rgba: &out_buf }, recording the timestamp of the first successful flush as first_ms; on S_FULL fires DecodeProgressiveEvent::Final { width, height, rgba: Vec cloned from out_buf } (ownership transfer so the callback can retain the final frame); on S_SUCCESS breaks. The decoder is destroyed via JxlDecoderDestroy in all exit paths (the function has no RAII wrapper, so early-return paths duplicate the Destroy call). Returns Some((first_ms, total_ms)) where first_ms is the elapsed time to the first flushed intermediate frame.

The sibling function decode_progressive_frames (not borrowed) is identical except it boxes each partial frame into an owned ProgressiveFrame { width, height, rgba: Vec<u8>, is_final: bool } and collects them into a Vec — for callers that need to retain every frame for comparison or export.""",

"es_validate": """Guard clauses that run synchronously before ANY libjxl call. Three checks in order. First, color_channels: the pixel layout (Channels::Rgb = 3, Channels::Gray = 1) must be 1 or 3 — libjxl's JxlEncoderSetBasicInfo cannot accept 0 or 2 colour channels (4-channel RGBA is handled by 3 colour channels + an interleaved alpha). A violation here returns EncodeError::Channels immediately. Second, alpha conflict: if Frame.alpha is Some (an interleaved fourth channel) and the extra channels list also contains an ExtraKind::Alpha (a planar separate alpha plane), both would claim the alpha slot — that is a caller error and returns EncodeError::Channels. Third, buffer dimensions: frame.color.len() must equal exactly width * height * interleaved_channels (1 for gray or 3 for RGB, +1 if interleaved alpha); and every planar extra channel buffer must be exactly width * height samples. A mismatch returns EncodeError::Size. These checks are total and cheap — they run on Rust-side counts before any C call, so a malformed Frame can never reach the C library and cause undefined behaviour or a libjxl internal error that is hard to diagnose.""",

"es_runner": """Attaches the pre-created thread runner to the encoder handle if one exists. The runner — a JxlThreadParallelRunner created once in Encoder::new when with_threads() was called — must be bound via JxlEncoderSetParallelRunner BEFORE JxlEncoderSetBasicInfo or the first frame call. libjxl enforces this ordering: if SetParallelRunner is called after SetBasicInfo it returns an error and the encode fails. The runner pointer is null for single-threaded encoders (created without with_threads()), so this step is a no-op for them. Binding here rather than in new() is intentional: the Encoder object may be reused across many encodes (encode calls JxlEncoderReset between them), and the runner binding is cleared by Reset — so it must be re-applied at the start of each encode. The runner itself is NOT re-created on each encode; only the binding is renewed. If SetParallelRunner fails (unusual — it only fails if the handle is in an invalid state), the encode returns EncodeError::Jxl.""",

"es_basic": """Commits the image geometry and sample-type contract to libjxl via JxlEncoderSetBasicInfo. The code starts with JxlEncoderInitBasicInfo (which fills a JxlBasicInfo struct with safe defaults — all zeros/false) and then overrides specific fields. xsize and ysize are the frame dimensions. bits_per_sample and exponent_bits are read from the Sample trait (u8 → 8/0, u16 → 16/0, f16 → 16/5, f32 → 32/8); this is how the encoder knows whether it is handling integer or floating-point pixels. num_color_channels is 1 for gray or 3 for RGB. num_extra_channels counts the interleaved-alpha slot (1 if present) plus the number of planar extra channels — libjxl treats all non-colour channels as extras and expects the count here so it can preallocate the right metadata slots. alpha_bits is set when alpha is present (matching bits_per_sample for integer types, 16 for floats); without this field libjxl does not allocate an alpha channel even if you try to bind one later. uses_original_profile is forced to true only under lossless encoding — this signals to libjxl that the colour profile is already the correct output profile and must not be adjusted during reconstruction; failing to set it under lossless silently produces a file that does not round-trip exactly. JxlEncoderSetBasicInfo then locks in this shape; calling SetBasicInfo twice or changing geometry mid-encode is an error. This step is the 'contract' — everything else (frame settings, pixel buffers) must be consistent with what was declared here.""",

"es_extrainfo": """Declares every planar extra channel individually before any pixel data is submitted. libjxl mandates that extra channels be declared via JxlEncoderInitExtraChannelInfo + JxlEncoderSetExtraChannelInfo for each channel, in order, before the first AddImageFrame call — submitting pixels for an undeclared extra channel is a hard error. The loop iterates frame.extra, calling InitExtraChannelInfo (which fills default metadata given the channel type: EXC_ALPHA, EXC_DEPTH, EXC_THERMAL, etc.) and then SetExtraChannelInfo at the channel's index. The index offset is load-bearing: if an interleaved alpha was declared in basic info (alpha_bits set), libjxl has already silently reserved slot 0 for it, so the first planar extra must be declared at index 1. The code accounts for this by starting the loop index after the interleaved-alpha slot. Depth channels, thermal channels, and spectral bands all take the same declaration path — only the ExtraChannelType discriminant differs. Missing this declaration for any channel causes SetExtraChannelBuffer in the bind-buffers step to fail with an opaque libjxl error that is hard to diagnose without knowing the ordering rule.""",

"es_color": """Sets the colour encoding so libjxl knows how to interpret the pixel values and how to tag the output file for decoders and viewers. The choice is: sRGB for integer sample types (u8, u16) because integer camera output is conventionally sRGB-gamma-encoded; linear sRGB for float types (f16, f32) because float pixels are typically in linear light (gamma-1.0) and applying sRGB gamma to them would double-encode the nonlinearity. The function JxlColorEncodingSetToSRGB or SetToLinearSRGB constructs a JxlColorEncoding struct (passing the is_gray flag so grayscale images are tagged correctly), and JxlEncoderSetColorEncoding commits it. If EncodeOptions.color is Some, that explicit encoding overrides the automatic choice — useful for wide-gamut (P3, Rec.2020) or custom ICC-profile workflows. This step must come after SetBasicInfo (the encoder needs to know the channel count to validate the encoding) and before AddImageFrame.""",

"es_fsettings": """Creates per-frame encode settings and applies the full set of quality/speed knobs. JxlEncoderFrameSettingsCreate allocates a JxlEncoderFrameSettings object tied to the handle. Effort (1–10) is applied first via JxlEncoderFrameSettingsSetOption(EFFORT) — this controls encoder CPU budget; effort 3 is the codebase default after measurement showed it optimal for speed+size. The rate decision is a three-way branch: if options say Lossless, JxlEncoderSetFrameLossless(true) is called and distance is NEVER touched; if Distance(d), SetFrameDistance(d) is called directly; if Quality(q), JxlEncoderDistanceFromQuality(q) converts to a Butteraugli distance first, then SetFrameDistance. The structural separation is intentional — an earlier bug (pre-BSD rewrite) could 'un-lossless' a frame by setting any distance value after lossless, because libjxl treats SetFrameDistance as an override. Keeping the three branches exclusive prevents that. After the rate decision, optional knobs are applied: progressive_dc (sets progressive detail level), group_order (tile scan order) with optional centering, and any FrameSettingId entries in EncodeOptions.extra_settings (Modular, Gaborish, EPF sharpening/deblocking, etc.). Frame settings are specific to one frame; creating them fresh each encode ensures no stale setting bleeds across encode_inner calls.""",

"es_addframe": """Hands the interleaved colour pixel data to libjxl zero-copy via JxlEncoderAddImageFrame. The call receives a JxlPixelFormat (channels count, S::data_type(), endianness from Frame.endianness, align=0) and a raw pointer + byte length into the frame's colour Vec. libjxl reads that memory in place during the encode — no copy is made across the Rust/C boundary. The frame's backing Vec must therefore stay alive and unmoved for the entire duration of encode_inner; the borrow of frame.color is what enforces this in Rust. The channel count passed here is interleaved_channels — which is num_color_channels + 1 if an interleaved alpha is present. The data_type comes from the Sample trait and determines whether libjxl reads bytes as u8, u16, f16, or f32. Endianness matters: the Frame stores native-endian samples, and the encoder is told JXL_NATIVE_ENDIAN so it does not byte-swap. This is the one step where the actual pixel content enters the codec; all prior steps only configure the shape and settings.""",

"es_extrabuf": """Binds each planar extra channel buffer zero-copy after the colour frame. JxlEncoderSetExtraChannelBuffer is called for each entry in frame.extra, with a JxlPixelFormat (1 channel, S::data_type(), native endian) and a raw pointer + byte length into the plane's Vec<S>. The channel index here must match the declaration index from the extra-channel-info step — they are ordered the same way. Like AddImageFrame, libjxl reads the Rust buffer in place; the frame's extra Vecs must stay alive for the encode duration. This step is a no-op (loop doesn't execute) when the frame has no planar extras — the common case for standard colour-only encodes. Skipping this step when extras were declared in es_extrainfo is a libjxl error; the channel count in basic info and the actual buffers bound here must match.""",

"es_close": """JxlEncoderCloseInput tells libjxl that all frames and extra-channel buffers have been submitted and encoding can proceed to completion. Without this call, JxlEncoderProcessOutput (the drain loop) stalls: it returns JXL_ENC_NEED_MORE_INPUT instead of producing bytes, because libjxl cannot know whether another frame is coming. In a single-frame encode this step is always required. In a multi-frame animation (not currently used in this codebase, which is single-frame only) CloseInput would be called after the last frame. The call itself is infallible — it just sets a flag inside the encoder state.""",

"es_process": """The output drain loop: starts with a 64 KiB Vec<u8> and calls JxlEncoderProcessOutput in a grow-loop until the full JXL codestream is produced. JxlEncoderProcessOutput takes a *mut u8 pointer and a remaining-capacity count, writes some bytes, and signals whether it needs more space or is done. On JXL_ENC_NEED_MORE_OUTPUT the loop grows the buffer — at minimum doubling capacity and adding 64 KiB — and calls again. The bytes-written count each iteration is (capacity_at_call - bytes_remaining_after_call), accumulating into a position counter. On JXL_ENC_SUCCESS the Vec is truncated to the written length and returned as the finished codestream. On any other status the loop returns EncodeError::Jxl carrying the libjxl error code from JxlEncoderGetError. The grow-loop is necessary because libjxl is a streaming C encoder that does not know the final compressed size in advance; it produces output in chunks. The 64 KiB starting size is a reasonable first-allocation that avoids reallocating for small images while not over-allocating for large ones.""",

"es_reset": """JxlEncoderReset is called by the public encode() method on EVERY exit path from encode_inner — success and every error variant alike. This is the invariant that makes Encoder reusable: after reset, the handle is in the same clean state as after JxlEncoderCreate, ready for another encode without re-creating the expensive thread runner. encode_inner focuses on the encode sequence; encode() owns the reset-on-every-path discipline. The architectural consequence: variant-set encoding (e.g. encode_variants* in casabio_encode.rs) can call encode_inner through one Encoder for all quality/effort variants of one image, paying the JxlEncoderCreate overhead once and the much-cheaper JxlEncoderReset between variants. If reset were omitted on error paths, any failed encode would poison the handle — subsequent calls to SetBasicInfo would fail silently or produce corrupt output, a class of bug that is very hard to reproduce.""",

}

by_id = {n['id']: n for n in m['nodes']}
for nid, desc in updates.items():
    if nid in by_id:
        by_id[nid]['desc'] = desc
        print(f'Updated {nid}: {len(desc)} chars')
    else:
        print(f'WARNING: {nid} not found')

with open('docs/ecosystem-map.model.json', 'w', encoding='utf-8') as f:
    json.dump(m, f, indent=2, ensure_ascii=False)
print('Done.')
