import type { MessagePort } from "node:worker_threads";
import type { Backend } from "./backend-selector.js";
import type { MsgDecodeStart } from "@casabio/jxl-core/protocol";
interface DecodeHandlerCallbacks {
    onSessionEnd: (sessionId: string) => void;
    port: MessagePort;
}
export declare class DecodeHandler {
    private readonly sessionId;
    private readonly opts;
    private readonly backend;
    private readonly port;
    private readonly callbacks;
    private state;
    private chunkQueue;
    private chunkReadIndex;
    private queueDepth;
    private queuedBytes;
    private cancelled;
    private ended;
    private inputClosed;
    private paused;
    private readonly stageStartMs;
    private firstPixelMetricPosted;
    private decoder;
    private disposePromise;
    private wakeResolve;
    private resumeResolve;
    private lastDrainPostedMs;
    private lastDrainAllowed;
    private pushLatencyEma;
    constructor(opts: MsgDecodeStart, backend: Backend, callbacks: DecodeHandlerCallbacks);
    onChunk(chunk: ArrayBuffer | Uint8Array | Buffer): void;
    onClose(): void;
    onCancel(_reason?: string): Promise<void>;
    onPause(): void;
    onResume(): void;
    private isTerminal;
    private finishSession;
    private clearInputQueue;
    private wake;
    private wakeResume;
    private run;
    private disposeActiveDecoder;
    private waitForChunk;
    private waitForResume;
    private takeNextChunk;
    private compactQueue;
    private feedDecoder;
    private adaptiveHwm;
    private maybePostDrain;
    private readDecoderEvents;
    private failSession;
    private checkBudget;
    private postBudgetExceeded;
    private postFirstPixelMetric;
    private postMetric;
}
export {};
//# sourceMappingURL=decode-handler.d.ts.map