import { CorpusManifest } from './types.js';

/**
 * jxl-test-corpus Manifest
 * 
 * Note: Corpus binaries are procedurally generated at build time and not checked into git.
 * Run "npm run generate:fixtures" in packages/jxl-test-corpus to generate local fixtures.
 */
export const manifest: CorpusManifest = {
  version: 1,
  fixtures: [
    {
      id: 'srgb-8bit',
      filename: 'srgb-8bit.jxl',
      license: 'CC0',
      width: 100,
      height: 100,
      bitsPerSample: 8,
      colorSpace: 'srgb',
      hasAlpha: false,
      hasIcc: false,
      hasExif: false,
      hasXmp: false,
      expectedPass: true,
      tags: ['basic', 'srgb'],
      sha256: 'c1dbe5e9bbf2bc2467e9d19ca26bbb2b22c92cec937483356e8d0e4758c5ad72',
      description: 'A basic 8-bit sRGB gradient without alpha.'
    },
    {
      id: 'srgb-alpha-8bit',
      filename: 'srgb-alpha-8bit.jxl',
      license: 'CC0',
      width: 100,
      height: 100,
      bitsPerSample: 8,
      colorSpace: 'srgb',
      hasAlpha: true,
      hasIcc: false,
      hasExif: false,
      hasXmp: false,
      expectedPass: true,
      tags: ['alpha'],
      sha256: 'f12dd729bbac0a5920283b521857f42822e4a42793325b990150314a85a6e2a5',
      description: 'An 8-bit sRGB gradient with a progressive alpha channel.'
    },
    {
      id: 'adobe-rgb-16bit',
      filename: 'adobe-rgb-16bit.jxl',
      license: 'Casabio-Internal',
      width: 100,
      height: 100,
      bitsPerSample: 16,
      colorSpace: 'adobe-rgb',
      hasAlpha: false,
      hasIcc: true,
      hasExif: true,
      hasXmp: true,
      expectedPass: true,
      tags: ['scientific', '16bit', 'icc', 'exif'],
      sha256: '047f20b29564a646f84f108954796a787bf3418509c2988c4f4fa7c79801d7f4',
      attribution: 'Casabio-Internal',
      occurrenceId: 'urn:lsid:casabio.org:occurrence:12345',
      description: 'A 16-bit wide-gamut calibration image with an embedded sRGB ICC profile plus mock Exif and Xmp metadata.'
    },
    {
      id: 'truncated-header',
      filename: 'truncated-header.jxl',
      license: 'CC0',
      bitsPerSample: 8,
      colorSpace: 'srgb',
      hasAlpha: false,
      hasIcc: false,
      hasExif: false,
      hasXmp: false,
      expectedPass: false,
      expectedError: 'JXL_DEC_ERROR', // expected fail substring
      tags: ['truncated', 'malformed'],
      sha256: 'bb51164afe84d75195791fa46c7eae51589185d93d429c5afe63405e2f320f29',
      description: 'A malformed JXL file truncated at byte 32 whose headers and dimensions are unknowable.'
    },
    {
      id: 'gray-ramp-16bit',
      filename: 'gray-ramp-16bit.jxl',
      license: 'CC0',
      width: 100,
      height: 100,
      bitsPerSample: 16,
      colorSpace: 'gray',
      hasAlpha: false,
      hasIcc: false,
      hasExif: false,
      hasXmp: false,
      expectedPass: true,
      tags: ['gray-ramp', 'colour-engine', '16bit'],
      sha256: '8946473bcdcfea5950a800f16950be5310644be9eeff9eb38a55a2951bbc7bd9',
      description: 'A 16-bit neutral-gray axis calibration ramp for testing non-Riemannian colour engine stability.'
    },
    {
      id: 'saturated-green-16bit',
      filename: 'saturated-green-16bit.jxl',
      license: 'CC0',
      width: 100,
      height: 100,
      bitsPerSample: 16,
      colorSpace: 'adobe-rgb',
      hasAlpha: false,
      hasIcc: false,
      hasExif: false,
      hasXmp: false,
      expectedPass: true,
      tags: ['gamut-green', 'colour-engine', '16bit'],
      sha256: '3f4ecaa53cc9b570fcd1fab041d7389e698ba982c8af9f64800849089d5dcb34',
      description: 'A saturated 16-bit green patch for profiling Molchanov residual density transform boundaries.'
    },
    {
      id: 'progressive-dc-truncated',
      filename: 'progressive-dc-truncated.jxl',
      license: 'CC0',
      bitsPerSample: 8,
      colorSpace: 'srgb',
      hasAlpha: false,
      hasIcc: false,
      hasExif: false,
      hasXmp: false,
      expectedPass: true,
      tags: ['progressive', 'dc-only', 'ar-latency'],
      sha256: '2f26cfaedb20954b38801fccb208a905da26887158fa751c2734363330cc74c4',
      description: 'A progressive JXL bitstream truncated after the DC layer for low-latency AR stream testing.'
    },
    {
      id: 'lossless-16bit',
      filename: 'lossless-16bit.jxl',
      license: 'CC0',
      width: 100,
      height: 100,
      bitsPerSample: 16,
      colorSpace: 'adobe-rgb',
      hasAlpha: false,
      hasIcc: false,
      hasExif: false,
      hasXmp: false,
      expectedPass: true,
      tags: ['lossless', 'archival', 'digital-twin', '16bit'],
      sha256: '5d2dfeab94b8f426041f5ec988e0cc83095cb76c0323abbaca86d35307da72b4',
      description: 'A 16-bit lossless archival/digital-twin specimen calibration frame.'
    },
    {
      id: 'multiview-a',
      filename: 'multiview-a.jxl',
      license: 'CC0',
      width: 100,
      height: 100,
      bitsPerSample: 8,
      colorSpace: 'srgb',
      hasAlpha: false,
      hasIcc: false,
      hasExif: false,
      hasXmp: false,
      expectedPass: true,
      tags: ['multiview', 'photogrammetry'],
      sha256: 'c49b1029c894a9071a193ecb1638f7056e46c1ba26fa5fd747b595edbfd5f9d7',
      groupId: 'multiview-specimen',
      viewIndex: 0,
      description: 'Viewpoint A of a multi-view photogrammetry synthetic specimen pair.'
    },
    {
      id: 'multiview-b',
      filename: 'multiview-b.jxl',
      license: 'CC0',
      width: 100,
      height: 100,
      bitsPerSample: 8,
      colorSpace: 'srgb',
      hasAlpha: false,
      hasIcc: false,
      hasExif: false,
      hasXmp: false,
      expectedPass: true,
      tags: ['multiview', 'photogrammetry'],
      sha256: '12ec1ea30c7be99807ec516e2b8cefe1308f91960b3db5d773c87da547d400b5',
      groupId: 'multiview-specimen',
      viewIndex: 1,
      description: 'Viewpoint B of a multi-view photogrammetry synthetic specimen pair.'
    }
  ]
};
